<?php
/**
 * Right-to-left stylesheets: generated, fresh, listed, and registered.
 *
 * Standalone, no WordPress. Every stylesheet the theme enqueues has an
 * rtlcss-generated sibling (X-rtl.css, committed, written by
 * scripts/build-rtl.js as part of `npm run build`) that WordPress swaps in
 * on RTL locales because the handle is registered with
 * wp_style_add_data( $handle, 'rtl', 'replace' ). What can rot:
 *
 *   1. a stylesheet is edited (or re-minified) and the sibling is not
 *      regenerated — caught by the SHA-1 stamp on the sibling's first line;
 *   2. a stylesheet is enqueued that scripts/build-rtl.js does not list;
 *   3. a stylesheet is enqueued without the registration.
 *
 * Run from the theme root:
 *   php tests/test-rtl-stylesheets.php
 *
 * @package Promptless_Theme
 * @since 1.3.5
 */
$run = 0; $ok = 0; $bad = [];
function eq( $expected, $actual, $label ) {
    global $run, $ok, $bad;
    $run++;
    if ( $expected === $actual ) { $ok++; echo "  ✓ {$label}\n"; }
    else { $bad[] = $label; echo "  ✗ {$label}\n      expected " . json_encode( $expected ) . "\n      actual   " . json_encode( $actual ) . "\n"; }
}

$root   = dirname( __DIR__ );
$assets = (string) file_get_contents( $root . '/inc/class-promptless-assets.php' );
$script = (string) file_get_contents( $root . '/scripts/build-rtl.js' );

// The files the generator lists.
preg_match_all( "/^\s*'([a-z0-9\/._-]+\.css)',/m", $script, $m );
$listed = $m[1];

echo "\nscripts/build-rtl.js lists every stylesheet the theme enqueues\n";
preg_match_all( "/wp_enqueue_style\(\s*'([a-z0-9-]+)'\s*,\s*(get_stylesheet_uri\(\)|PROMPTLESS_THEME_URI\s*\.\s*'\/([a-z0-9\/._-]+\.css)')/s", $assets, $e, PREG_OFFSET_CAPTURE | PREG_SET_ORDER );
eq( true, count( $e ) >= 9, 'found the enqueue sites (' . count( $e ) . ')' );
foreach ( $e as $hit ) {
    $handle = $hit[1][0];
    $file   = isset( $hit[3] ) && $hit[3][0] !== '' ? $hit[3][0] : 'style.css';
    eq( true, in_array( $file, $listed, true ), "{$file} is listed in scripts/build-rtl.js" );
    $after = substr( $assets, $hit[0][1], 900 );
    eq( 1, preg_match( '/wp_style_add_data\(\s*\'' . preg_quote( $handle, '/' ) . '\'\s*,\s*\'rtl\'\s*,\s*\'replace\'\s*\)/', $after ), "'{$handle}' ({$file}) registers its RTL sibling" );
}
eq( true, in_array( 'assets/css/editor-style.css', $listed, true ), 'editor-style.css is listed (core adds its -rtl sibling itself)' );

echo "\nEvery listed stylesheet has a sibling generated from its current content\n";
foreach ( $listed as $rel ) {
    $src = $root . '/' . $rel;
    $rtl = preg_replace( '/\.css$/', '-rtl.css', $src );
    if ( ! file_exists( $src ) ) { eq( true, false, "{$rel} exists" ); continue; }
    if ( ! file_exists( $rtl ) ) { eq( true, false, "{$rel} has a -rtl.css sibling — run npm run build" ); continue; }
    $first = strtok( (string) file_get_contents( $rtl ), "\n" );
    $stamped = preg_match( '/^\/\* rtl: generated by scripts\/build-rtl\.js from ' . preg_quote( basename( $rel ), '/' ) . ' \(sha1 ([0-9a-f]{40})\)/', (string) $first, $s ) === 1;
    eq( true, $stamped, "{$rel}: sibling carries the generator stamp" );
    if ( $stamped ) {
        eq( sha1_file( $src ), $s[1], "{$rel}: sibling was generated from the current file (else run npm run build)" );
    }
}

echo "\n{$ok}/{$run} passed" . ( $bad ? ' — FAILED: ' . implode( ', ', $bad ) : '' ) . "\n";
exit( $bad ? 1 : 0 );
