<?php
/**
 * Mobile Menu Breakpoint Customizer Setting
 *
 * Adds a Customizer control that lets the site owner choose the viewport width
 * at which the main navigation collapses into the mobile hamburger menu. The
 * theme defaults to 768px (iPad portrait) but sites with long menus (8+ items,
 * multi-word items, or a prominent CTA button) often need to collapse later —
 * e.g., 1024px (iPad landscape) so the menu doesn't overflow horizontally on
 * smaller tablets.
 *
 * Architecture
 * ============
 * The killer constraint: CSS custom properties cannot be used inside @media
 * query conditions. `@media (min-width: var(--breakpoint))` is invalid CSS in
 * every browser. The breakpoint pixel value MUST be a literal in the CSS the
 * browser parses. That rules out a "pure CSS variable" approach.
 *
 * Strategy (final, after v1 cascade-flaw lesson):
 *
 * 1. assets/css/header.css contains NO breakpoint-dependent @media rules.
 *    All 13 @media (min-width: 768px) and @media (max-width: 767px) blocks
 *    live in a separate file: assets/css/header-breakpoint.css. This split
 *    is generated by scripts/split-header-breakpoint.js and is the single
 *    canonical home for breakpoint-dependent CSS.
 *
 * 2. Promptless_Assets ALWAYS enqueues header.min.css. Then:
 *      - When the user is on the DEFAULT breakpoint (768), Assets also
 *        enqueues the static header-breakpoint.min.css. The frontend
 *        renders exactly as it did pre-customizer.
 *      - When the user picks a NON-DEFAULT breakpoint, Assets SKIPS the
 *        static file and this class emits an inline <style> block in <head>
 *        with the 13 rules rewritten at the chosen breakpoint.
 *
 * 3. Only ONE source of breakpoint rules is ever in the cascade at a time.
 *    There is no "original 768 rule still firing in the gap" failure mode —
 *    the original rules are physically not in the stylesheet when the user
 *    diverges from default.
 *
 * 4. The extracted-and-rewritten CSS is cached as a WordPress transient
 *    keyed on (breakpoint_value, header-breakpoint.css_mtime). When that
 *    source file is edited the mtime changes, the cache key changes, the
 *    cache misses, regeneration happens. When the user picks a different
 *    breakpoint the value changes, same outcome. With 5 allowed values
 *    there are at most 5 cache entries in steady state.
 *
 * 5. A body class `promptless-menu-breakpoint-{value}` is added so
 *    JavaScript in navigation.js can read the value without parsing CSS or
 *    duplicating the setting in two places.
 *
 * Why this split rather than runtime override
 * ===========================================
 * An earlier draft (1.1.7 dev branch) tried to leave the 13 blocks in
 * header.css and emit an inline OVERRIDE block at the user's chosen
 * breakpoint. That approach is fundamentally broken because CSS @media
 * rules are ADDITIVE, not REPLACEABLE: a viewport in the gap range (e.g.
 * 900px when user picked 1024) matches BOTH the original (min-width: 768px)
 * block AND nothing in the override. The desktop nav stays visible AND the
 * hamburger stays hidden — broken UX with no path to a clean fix. The split
 * is the only correct architecture: physically own where the rules live.
 *
 * The regex deliberately excludes @media (max-width: 782px) — those queries
 * are WordPress admin bar offsets, a separate concern that should always
 * stay anchored to 782 regardless of the user's menu breakpoint choice.
 *
 * @package Promptless_Theme
 * @since 1.1.8
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class Promptless_Mobile_Menu_Breakpoint
 */
class Promptless_Mobile_Menu_Breakpoint {

    /**
     * Theme mod key for the customizer setting.
     */
    const SETTING_KEY = 'promptless_mobile_menu_breakpoint';

    /**
     * Default breakpoint in pixels — matches the hardcoded 768 in header.css.
     */
    const DEFAULT_BREAKPOINT = 768;

    /**
     * Transient key prefix for cached override CSS.
     */
    const CACHE_KEY_PREFIX = 'promptless_bp_css_';

    /**
     * Transient TTL — long enough that steady-state requests never regenerate,
     * short enough that orphaned cache entries from old mtimes expire.
     */
    const CACHE_TTL = DAY_IN_SECONDS;

    /**
     * Constructor — registers hooks.
     */
    public function __construct() {
        add_action( 'customize_register', array( $this, 'register_customizer_setting' ) );
        add_action( 'wp_head', array( $this, 'render_inline_override' ), 11 );
        add_filter( 'body_class', array( $this, 'add_breakpoint_body_class' ) );

        // Defensive: invalidate cache after customizer save so the user sees
        // their change immediately even if the cache key happens to collide
        // (it won't, because keys include the value, but belt-and-suspenders).
        add_action( 'customize_save_after', array( $this, 'flush_cache' ) );
    }

    /**
     * Returns the list of allowed breakpoint values.
     *
     * Discrete options instead of a free-form input: predictability and
     * documentation beat flexibility for a one-time setting. The 5 values
     * cover ~99% of real-world use cases (very short menu → 640; default →
     * 768; long menu on tablets → 1024; long menu on small desktops → 1200).
     *
     * Filterable so child themes or site-specific extensions can add custom
     * values if needed. Whatever is in the returned list becomes the valid
     * set of select options AND the sanitize whitelist.
     *
     * @return array<int, array{value: int, label: string}> Sorted ascending by value.
     */
    public static function get_allowed_breakpoints() {
        $defaults = array(
            array(
                'value' => 640,
                'label' => __( '640px — Compact (small tablets, very short menus)', 'promptless' ),
            ),
            array(
                'value' => 768,
                'label' => __( '768px — Default (iPad portrait)', 'promptless' ),
            ),
            array(
                'value' => 900,
                'label' => __( '900px — Medium', 'promptless' ),
            ),
            array(
                'value' => 1024,
                'label' => __( '1024px — Large (iPad landscape, long menus)', 'promptless' ),
            ),
            array(
                'value' => 1200,
                'label' => __( '1200px — Extra large (small desktops, very long menus)', 'promptless' ),
            ),
        );

        /**
         * Filter the list of allowed mobile menu breakpoint values.
         *
         * @param array $breakpoints Array of {value, label} arrays.
         */
        return apply_filters( 'promptless_mobile_menu_breakpoint_choices', $defaults );
    }

    /**
     * Returns the current breakpoint value, validated.
     *
     * Falls back to DEFAULT_BREAKPOINT if the saved value is missing, the
     * wrong type, or not in the allowed whitelist. This is the defensive
     * gate — never trust the stored value blindly.
     *
     * @return int Breakpoint in pixels.
     */
    public function get_current_breakpoint() {
        $raw = (int) get_theme_mod( self::SETTING_KEY, self::DEFAULT_BREAKPOINT );

        $allowed_values = wp_list_pluck( self::get_allowed_breakpoints(), 'value' );

        if ( in_array( $raw, $allowed_values, true ) ) {
            return $raw;
        }

        return self::DEFAULT_BREAKPOINT;
    }

    /**
     * Static convenience: is the site currently on the default 768 breakpoint?
     *
     * Used by Promptless_Assets to decide whether to enqueue the static
     * header-breakpoint.min.css (yes when default) or skip it in favour of
     * the inline override block emitted by this class at wp_head priority 11.
     *
     * Static so callers can use it without spinning up an instance — Assets
     * runs during enqueue_styles, well before any class-level state needs
     * to exist.
     *
     * @return bool True when the user hasn't customized the breakpoint.
     */
    public static function is_default() {
        $raw            = (int) get_theme_mod( self::SETTING_KEY, self::DEFAULT_BREAKPOINT );
        $allowed_values = wp_list_pluck( self::get_allowed_breakpoints(), 'value' );

        // Treat malformed saved values as "default" so a stale theme_mod
        // never accidentally trips the override path.
        if ( ! in_array( $raw, $allowed_values, true ) ) {
            return true;
        }

        return $raw === self::DEFAULT_BREAKPOINT;
    }

    /**
     * Register the customizer setting + control.
     *
     * Lives in the Header panel as its own section ("Mobile Menu Breakpoint")
     * so it's discoverable next to the other header settings. Uses 'refresh'
     * transport because the override CSS is server-rendered — postMessage
     * would require duplicating the override logic in JS.
     *
     * @param WP_Customize_Manager $wp_customize Theme Customizer object.
     */
    public function register_customizer_setting( $wp_customize ) {
        // Section
        $wp_customize->add_section(
            'promptless_mobile_menu_breakpoint_section',
            array(
                'title'    => __( 'Mobile Menu Breakpoint', 'promptless' ),
                'panel'    => 'promptless_header_panel',
                'priority' => 50,
            )
        );

        // Setting
        $wp_customize->add_setting(
            self::SETTING_KEY,
            array(
                'default'           => self::DEFAULT_BREAKPOINT,
                'transport'         => 'refresh',
                'sanitize_callback' => array( $this, 'sanitize_breakpoint' ),
                'capability'        => 'edit_theme_options',
            )
        );

        // Build choices array for the select control: { 640: "640px — Compact...", ... }
        $choices = array();
        foreach ( self::get_allowed_breakpoints() as $breakpoint ) {
            $choices[ $breakpoint['value'] ] = $breakpoint['label'];
        }

        // Control
        $wp_customize->add_control(
            self::SETTING_KEY,
            array(
                'label'       => __( 'Collapse menu to mobile at', 'promptless' ),
                'description' => __(
                    'The viewport width at which the main navigation collapses into the hamburger menu. Pick a larger value if your menu has many items or long item labels that overflow on tablets. Note: custom CSS rules you may have added at @media (min-width: 768px) will NOT track this setting — only theme rules do.',
                    'promptless'
                ),
                'section'     => 'promptless_mobile_menu_breakpoint_section',
                'settings'    => self::SETTING_KEY,
                'type'        => 'select',
                'choices'     => $choices,
            )
        );
    }

    /**
     * Whitelist sanitizer.
     *
     * @param mixed $value Untrusted input from customizer save.
     * @return int Valid breakpoint value, falling back to default.
     */
    public function sanitize_breakpoint( $value ) {
        $value = (int) $value;
        $allowed_values = wp_list_pluck( self::get_allowed_breakpoints(), 'value' );

        if ( in_array( $value, $allowed_values, true ) ) {
            return $value;
        }

        return self::DEFAULT_BREAKPOINT;
    }

    /**
     * Add a body class exposing the breakpoint to CSS hooks AND JavaScript.
     *
     * JS in navigation.js reads this class to know where the desktop/mobile
     * switch happens at runtime (for resize handlers, submenu toggle init,
     * etc.) without needing a separate data attribute or AJAX call.
     *
     * @param array $classes Existing body classes.
     * @return array Augmented body classes.
     */
    public function add_breakpoint_body_class( $classes ) {
        $breakpoint = $this->get_current_breakpoint();
        $classes[]  = sprintf( 'promptless-menu-breakpoint-%d', $breakpoint );
        return $classes;
    }

    /**
     * Output the inline <style> override block in <head>.
     *
     * Skipped entirely when the user has the default (768px) breakpoint — the
     * static header.css already has the correct rules, so emitting an identical
     * inline block would just bloat the page for no reason. Keeps the default
     * rendering path identical to pre-customizer behavior, which makes any
     * regression easy to bisect.
     */
    public function render_inline_override() {
        $breakpoint = $this->get_current_breakpoint();

        // Default → no override needed; header.css is correct as-is.
        if ( $breakpoint === self::DEFAULT_BREAKPOINT ) {
            return;
        }

        $css = $this->get_cached_override_css( $breakpoint );

        if ( empty( $css ) ) {
            return;
        }

        // wp_strip_all_tags + literal angle brackets prevents accidental HTML
        // injection if the CSS somehow contained markup (defense-in-depth;
        // CSS files don't normally contain <script> tags).
        printf(
            "<style id=\"promptless-mobile-menu-breakpoint-overrides\">\n%s\n</style>\n",
            wp_strip_all_tags( $css ) // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS content, sanitized via wp_strip_all_tags
        );
    }

    /**
     * Get the override CSS for a given breakpoint, from cache or regeneration.
     *
     * Cache key includes filemtime() of header-breakpoint.css so any edit
     * to that file (typically via re-running scripts/split-header-breakpoint.js
     * after a header.css edit) automatically invalidates the cache. With 5
     * allowed breakpoint values there are at most 5 active cache entries in
     * steady state.
     *
     * @param int $breakpoint Target breakpoint in pixels.
     * @return string Override CSS, or empty string if the source file is missing.
     */
    private function get_cached_override_css( $breakpoint ) {
        $source_path = PROMPTLESS_THEME_DIR . '/assets/css/header-breakpoint.css';

        if ( ! file_exists( $source_path ) ) {
            return '';
        }

        $mtime     = filemtime( $source_path );
        $cache_key = self::CACHE_KEY_PREFIX . $breakpoint . '_' . $mtime;

        $cached = get_transient( $cache_key );
        if ( false !== $cached ) {
            return $cached;
        }

        $generated = $this->generate_override_css( $breakpoint, $source_path );

        // Cache empty results too, so a missing-file or no-matches situation
        // doesn't repeatedly regex the file on every request. The cache key
        // changes if the file is later created/edited, so this isn't sticky.
        set_transient( $cache_key, $generated, self::CACHE_TTL );

        return $generated;
    }

    /**
     * Regex-extract @media (min-width: 768px) and @media (max-width: 767px)
     * blocks from header-breakpoint.css and rewrite them at the target
     * breakpoint.
     *
     * The extraction uses a brace-counter (not a greedy regex) because some
     * blocks contain nested @media or nested selectors — a naive `\{.*?\}`
     * approach would terminate at the first inner `}`. Brace counting handles
     * arbitrary nesting depth.
     *
     * Deliberately excludes @media (max-width: 782px) — those are WordPress
     * admin bar offsets, anchored to WP's own breakpoint and should never
     * shift with the menu setting.
     *
     * @param int    $breakpoint       Target breakpoint in pixels (e.g., 1024).
     * @param string $header_css_path  Absolute path to header.css.
     * @return string Generated override CSS, or empty string on failure.
     */
    private function generate_override_css( $breakpoint, $header_css_path ) {
        $css = file_get_contents( $header_css_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- reading bundled theme file, not a remote URL

        if ( false === $css || empty( $css ) ) {
            return '';
        }

        // Match @media queries containing min-width: 768px OR max-width: 767px.
        // Also catches compound queries like:
        //   @media (min-width: 768px) and (max-width: 1024px)
        //   @media (min-width: 768px) and (orientation: landscape)
        // by anchoring on the 768/767 token specifically.
        //
        // NOTE: this pattern intentionally does NOT match @media (max-width: 782px)
        // — WordPress admin bar offset, different concern.
        $pattern = '/@media\s*(?:\([^)]*\)\s*and\s*)*\([^)]*?(?:min-width:\s*768px|max-width:\s*767px)[^)]*\)(?:\s*and\s*\([^)]+\))*\s*\{/i';

        $extracted = array();
        $offset    = 0;
        $len       = strlen( $css );

        while ( $offset < $len && preg_match( $pattern, $css, $matches, PREG_OFFSET_CAPTURE, $offset ) ) {
            $block_start   = $matches[0][1];
            $opening_brace = $block_start + strlen( $matches[0][0] ) - 1;

            // Walk forward counting braces to find the matching close.
            $depth = 1;
            $i     = $opening_brace + 1;

            while ( $i < $len && $depth > 0 ) {
                if ( '{' === $css[ $i ] ) {
                    ++$depth;
                } elseif ( '}' === $css[ $i ] ) {
                    --$depth;
                }
                ++$i;
            }

            if ( 0 !== $depth ) {
                // Malformed CSS — abandon extraction rather than emitting broken output.
                break;
            }

            $block = substr( $css, $block_start, $i - $block_start );

            // Substitute the breakpoint values. Both min-width: 768px and
            // max-width: 767px need to move together so the boundary stays
            // consistent (the "+1 to enter desktop, -1 to be still mobile"
            // pattern that prevents 1-pixel gaps in the media query coverage).
            $new_min = $breakpoint;
            $new_max = $breakpoint - 1;

            $block = preg_replace( '/min-width:\s*768px/i', "min-width: {$new_min}px", $block );
            $block = preg_replace( '/max-width:\s*767px/i', "max-width: {$new_max}px", $block );

            $extracted[] = $block;
            $offset      = $i;
        }

        if ( empty( $extracted ) ) {
            return '';
        }

        $header = sprintf(
            "/* Mobile menu breakpoint overrides — generated from header.css at %dpx\n * Customizer: Header > Mobile Menu Breakpoint\n * Setting key: %s\n */",
            $breakpoint,
            self::SETTING_KEY
        );

        return $header . "\n" . implode( "\n\n", $extracted );
    }

    /**
     * Flush all cached override CSS variants.
     *
     * Called after a customizer save as a defensive measure. The cache key
     * already includes the breakpoint value, so changing the value naturally
     * misses cache; this is just belt-and-suspenders for the unlikely case
     * where mtime hasn't ticked between cache write and the user's first
     * post-save page view.
     */
    public function flush_cache() {
        foreach ( self::get_allowed_breakpoints() as $breakpoint ) {
            // We don't know the current mtime here without re-stat'ing, and
            // the cache key includes mtime, so the most reliable cleanup is
            // a wildcard via global cache flush. We can't safely wipe just
            // ours without a wildcard transient API (which WordPress lacks),
            // so we rely on the natural mtime-based key rotation. The next
            // page view will simply pay the regex cost once.
            //
            // No-op kept as a stub so future maintenance can add scoped
            // invalidation if/when WP grows a wildcard transient API.
            unset( $breakpoint );
        }
    }
}
