/**
 * Right-to-left stylesheet build.
 *
 * Generates X-rtl.css beside every stylesheet the theme enqueues, with
 * rtlcss — the tool WordPress core and wp-scripts use. WordPress swaps the
 * sibling in on RTL locales because each handle is registered with
 * wp_style_add_data( $handle, 'rtl', 'replace' ) (inc/class-promptless-assets.php).
 *
 * Runs as part of `npm run build`, AFTER minification, because the theme
 * enqueues the .min.css files: the RTL sibling of header.min.css is
 * header.min-rtl.css, generated from the minified source so the two match.
 *
 * Each generated file starts with a stamp carrying the SHA-1 of its source;
 * tests/test-rtl-stylesheets.php fails when a source changed without this
 * script being re-run. The generated files are committed. Never edit one.
 *
 * @package Promptless_Theme
 * @since 1.3.5
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const rtlcss = require('rtlcss');

// Every stylesheet the theme enqueues or hands to the editor (keep in step
// with inc/class-promptless-assets.php and add_editor_style()).
const sources = [
    'style.css',
    'assets/css/header.min.css',
    'assets/css/header-breakpoint.min.css',
    'assets/css/footer.min.css',
    'assets/css/search.min.css',
    'assets/css/archive.min.css',
    'assets/css/woocommerce.min.css',
    'assets/css/breadcrumbs.min.css',
    'assets/css/announcement-bar.css',
    'assets/css/editor-style.css',
];

const themeRoot = path.resolve(__dirname, '..');

for (const rel of sources) {
    const src = path.join(themeRoot, rel);
    if (!fs.existsSync(src)) {
        console.error(`✗ missing source: ${rel}`);
        process.exitCode = 1;
        continue;
    }
    const css = fs.readFileSync(src, 'utf8');
    const sha1 = crypto.createHash('sha1').update(css).digest('hex');
    const out = src.replace(/\.css$/, '-rtl.css');
    const stamp = `/* rtl: generated by scripts/build-rtl.js from ${path.basename(rel)} (sha1 ${sha1}) - do not edit; run npm run build */\n`;
    fs.writeFileSync(out, stamp + rtlcss.process(css));
    console.log(`✓ ${rel} → ${path.relative(themeRoot, out)}`);
}
